src/test/java/com/autonomouslogic/everef/esi/EsiRateLimitInterceptorTest.java, src/test/java/com/autonomouslogic/everef/esi/RateLimitInterceptorTest.java, src/test/java/com/autonomouslogic/everef/test/TestComponent.java, src/test/java/com/autonomouslogic/everef/test/TestDataUtil.java
Closes https://github.com/autonomouslogic/eve-ref/issues/42.
=> test: Testing for the rate limit interceptor

src/main/java/com/autonomouslogic/everef/esi/EsiLimitExceededInterceptor.java, src/main/java/com/autonomouslogic/everef/inject/OkHttpModule.java, src/test/java/com/autonomouslogic/everef/esi/EsiLimitExceededInterceptorTest.java, src/test/java/com/autonomouslogic/everef/test/TestComponent.java, src/test/java/com/autonomouslogic/everef/test/TestDataUtil.java
Closes https://github.com/autonomouslogic/eve-ref/issues/41.
=> fix: ESI 420 interceptor works properly

.dockerignore, .github/workflows/build.yml, .github/workflows/renovate.yml, .gitignore, Makefile, renovate.json
Fixes https://github.com/autonomouslogic/eve-ref/issues/51.
=> ci: Fix Renovate Configuration

renovate.json
=> ci: Removed special package rules for Renovate

src/main/java/com/autonomouslogic/everef/cli/DataIndex.java, src/main/java/com/autonomouslogic/everef/cli/marketorders/ScrapeMarketOrders.java, src/main/java/com/autonomouslogic/everef/config/Configs.java, src/main/java/com/autonomouslogic/everef/util/S3Util.java
Related to https://github.com/autonomouslogic/eve-ref/issues/61
=> feat: Changed index cache max-age and added it to market orders

src/main/java/com/autonomouslogic/everef/cli/DataIndex.java, src/main/java/com/autonomouslogic/everef/cli/PublishRefData.java, src/main/java/com/autonomouslogic/everef/cli/marketorders/ScrapeMarketOrders.java, src/main/java/com/autonomouslogic/everef/cli/publiccontracts/ScrapePublicContracts.java, src/main/java/com/autonomouslogic/everef/cli/refdata/BuildRefData.java, src/main/java/com/autonomouslogic/everef/s3/ListedS3Object.java, src/main/java/com/autonomouslogic/everef/s3/S3Adapter.java, src/main/java/com/autonomouslogic/everef/url/DataUrl.java, src/main/java/com/autonomouslogic/everef/url/FileUrl.java, src/main/java/com/autonomouslogic/everef/url/HttpUrl.java, src/main/java/com/autonomouslogic/everef/url/S3Url.java, src/main/java/com/autonomouslogic/everef/url/UrlParser.java, src/test/java/com/autonomouslogic/everef/cli/PublishRefDataTest.java, src/test/java/com/autonomouslogic/everef/cli/marketorders/ScrapeMarketOrdersTest.java, src/test/java/com/autonomouslogic/everef/cli/publiccontracts/ScrapePublicContractsTest.java, src/test/java/com/autonomouslogic/everef/cli/refdata/BuildRefDataTest.java, src/test/java/com/autonomouslogic/everef/test/MockS3Adapter.java, src/test/java/com/autonomouslogic/everef/url/FileUrlTest.java, src/test/java/com/autonomouslogic/everef/url/HttpUrlTest.java, src/test/java/com/autonomouslogic/everef/url/S3UrlTest.java, src/test/java/com/autonomouslogic/everef/url/UrlParserTest.java, src/test/resources/com/autonomouslogic/everef/url/FileUrlTest/file-resolve.csv, src/test/resources/com/autonomouslogic/everef/url/FileUrlTest/file-urls.csv, src/test/resources/com/autonomouslogic/everef/url/HttpUrlTest/http-resolve.csv, src/test/resources/com/autonomouslogic/everef/url/HttpUrlTest/http-urls.csv, src/test/resources/com/autonomouslogic/everef/url/S3UrlTest/s3-resolve.csv, src/test/resources/com/autonomouslogic/everef/url/S3UrlTest/s3-urls.csv
=> refactor: Data access

.releaserc, publish.sh
=> feat!: Basic publish setup

.github/workflows/specs.yml, Makefile, build.gradle, gradle.properties, spec/reference-data.yaml, src/main/java/com/autonomouslogic/everef/cli/CommandRunner.java, src/main/java/com/autonomouslogic/everef/cli/PublishRefData.java, src/main/java/com/autonomouslogic/everef/cli/VerifyRefDataModels.java, src/main/java/com/autonomouslogic/everef/model/ReferenceEntry.java, src/main/java/com/autonomouslogic/everef/refdata/DogmaTypeAttribute.java, src/main/java/com/autonomouslogic/everef/refdata/DogmaTypeEffect.java, src/main/java/com/autonomouslogic/everef/refdata/InventoryType.java, src/main/java/com/autonomouslogic/everef/refdata/InventoryTypeTraits.java, src/main/java/com/autonomouslogic/everef/refdata/ReferenceDataSpec.java, src/main/java/com/autonomouslogic/everef/refdata/TraitBonus.java, src/main/java/com/autonomouslogic/everef/util/RefDataUtil.java
=> feat: Basic reference data OpenAPI spec and model verifier

src/main/java/com/autonomouslogic/everef/cli/DataIndex.java, src/main/java/com/autonomouslogic/everef/s3/ListedS3Object.java, src/main/resources/pug/data/index.pug, src/test/java/com/autonomouslogic/everef/cli/DataIndexTest.java, src/test/java/com/autonomouslogic/everef/test/MockS3Adapter.java
=> fix: Fixed data index size and last-modified

spec/reference-data.yaml, src/main/java/com/autonomouslogic/everef/refdata/MarketGroup.java, src/main/java/com/autonomouslogic/everef/refdata/ReferenceDataSpec.java, src/main/resources/refdata.yaml, src/test/resources/com/autonomouslogic/everef/cli/refdata/esi/EsiLoaderTest/market-group-1376.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/sde/SdeLoaderTest/market-group-1376.json, src/test/resources/refdata/esi/data/tranquility/markets/groups.en-us.yaml, src/test/resources/refdata/refdata/market-group-1376.json, src/test/resources/refdata/sde/fsd/marketGroups.yaml
=> feat: Market group reference data

ui/components/navbar.vue, ui/i18n.config.ts, ui/nuxt.config.ts, ui/package-lock.json, ui/package.json, ui/pages/types/[id].vue, ui/tsconfig.json
* Reverted to `@nuxtjs/i18n` to `8.0.0-beta.10` (from `8.0.0-beta.12`)
* Copied the config from `i18n.config.ts` into `nuxt.config.ts`, sometime after beta 10 this was moved to a separate file, but beta 10 doesn't accept that.
* There's an open issue for this at https://github.com/nuxt-modules/i18n/issues/2031
=> fix: Revert @nuxtjs/i18n to fix Cloudflare Page deploy

ui/.gitignore, ui/openapitools.json, ui/pages/types/[id].vue, ui/pages/types/[typeId].vue, ui/refdata/index.ts
=> fix: Use OpenAPI-generated client properly

docs/src/datasets/reference-data.md, spec/reference-data.yaml, src/main/java/com/autonomouslogic/everef/refdata/MetaGroup.java, src/main/java/com/autonomouslogic/everef/refdata/ReferenceDataSpec.java, src/main/resources/refdata.yaml, src/test/resources/com/autonomouslogic/everef/cli/refdata/sde/SdeLoaderTest/meta-group-1.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/sde/SdeLoaderTest/meta-group-15.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/sde/SdeLoaderTest/meta-group-2.json, src/test/resources/refdata/refdata/meta-group-1.json, src/test/resources/refdata/refdata/meta-group-15.json, src/test/resources/refdata/refdata/meta-group-2.json, src/test/resources/refdata/sde/fsd/metaGroups.yaml
=> feat: Meta groups reference data

spec/reference-data.yaml, src/main/java/com/autonomouslogic/everef/cli/refdata/post/BlueprintDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/MarketGroupsDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/SkillDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/TypesDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/VariationsDecorator.java, src/main/java/com/autonomouslogic/everef/refdata/DogmaAttribute.java, src/main/java/com/autonomouslogic/everef/refdata/DogmaEffect.java, src/main/java/com/autonomouslogic/everef/refdata/DogmaTypeAttribute.java, src/main/java/com/autonomouslogic/everef/refdata/DogmaTypeEffect.java, src/main/java/com/autonomouslogic/everef/refdata/InventoryCategory.java, src/main/java/com/autonomouslogic/everef/refdata/InventoryType.java, src/main/java/com/autonomouslogic/everef/refdata/InventoryTypeTraits.java, src/main/java/com/autonomouslogic/everef/refdata/MetaGroup.java, src/main/java/com/autonomouslogic/everef/refdata/ModifierInfo.java, src/main/java/com/autonomouslogic/everef/refdata/Mutaplasmid.java, src/main/java/com/autonomouslogic/everef/refdata/MutaplasmidDogmaModifications.java, src/main/java/com/autonomouslogic/everef/refdata/MutaplasmidTypeMapping.java, src/main/java/com/autonomouslogic/everef/refdata/ProducingBlueprint.java, src/main/java/com/autonomouslogic/everef/refdata/ReferenceDataSpec.java, src/main/java/com/autonomouslogic/everef/refdata/Skill.java, src/main/java/com/autonomouslogic/everef/refdata/TraitBonus.java, src/main/java/com/autonomouslogic/everef/refdata/Unit.java, src/test/resources/refdata/refdata/type-22430.json, src/test/resources/refdata/refdata/type-22431.json, src/test/resources/refdata/refdata/type-645.json
=> refactor: Changed IDs to longs and renamed creating_blueprints to produced_by_blueprints

spec/reference-data.yaml, src/main/java/com/autonomouslogic/everef/cli/refdata/BuildRefData.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/OreVariationsDecorator.java, src/main/java/com/autonomouslogic/everef/refdata/InventoryType.java, src/main/resources/refdata.yaml, src/test/resources/com/autonomouslogic/everef/cli/refdata/esi/EsiLoaderTest/dogma-attribute-2699.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/esi/EsiLoaderTest/dogma-attribute-2711.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/esi/EsiLoaderTest/type-1230.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/esi/EsiLoaderTest/type-17470.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/esi/EsiLoaderTest/type-17471.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/sde/SdeLoaderTest/dogma-attribute-2699.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/sde/SdeLoaderTest/dogma-attribute-2711.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/sde/SdeLoaderTest/type-1230.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/sde/SdeLoaderTest/type-17470.json, src/test/resources/com/autonomouslogic/everef/cli/refdata/sde/SdeLoaderTest/type-17471.json, src/test/resources/refdata/esi/data/tranquility/dogma/attributes.yaml, src/test/resources/refdata/esi/data/tranquility/universe/types.en-us.yaml, src/test/resources/refdata/esi/data/tranquility/universe/types.fr.yaml, src/test/resources/refdata/refdata/dogma-attribute-2699.json, src/test/resources/refdata/refdata/dogma-attribute-2711.json, src/test/resources/refdata/refdata/type-1230.json, src/test/resources/refdata/refdata/type-17470.json, src/test/resources/refdata/refdata/type-17471.json, src/test/resources/refdata/sde/fsd/dogmaAttributes.yaml, src/test/resources/refdata/sde/fsd/typeIDs.yaml
=> feat: Ore variations

ui/assets/css/tailwind.css, ui/components/helpers/TypeLink.vue, ui/components/navbar.vue, ui/components/types/CategoryLink.vue, ui/components/types/GroupLink.vue, ui/components/types/traits/TypeTraits.vue, ui/pages/index.vue, ui/tailwind.config.js
=> feat: Super simple Tailwind theming

ui/assets/css/tailwind.css, ui/components/cards/BasicsCard.vue, ui/components/cards/CardWrapper.vue, ui/components/cards/CardsContainer.vue, ui/components/cards/DogmaCard.vue, ui/components/cards/TraitsCard.vue, ui/components/navbar.vue, ui/pages/types/[typeId].vue
=> feat: Basic reusable cards

ui/components/Footer.vue
=> fix: Footer icon fixes

src/main/java/com/autonomouslogic/everef/cli/refdata/BuildRefData.java, src/main/java/com/autonomouslogic/everef/cli/refdata/RefDataMerger.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/BlueprintDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/VariationsDecorator.java, src/main/java/com/autonomouslogic/everef/mvstore/MVStoreUtil.java, src/test/resources/log4j2.properties
For getting more information to solve https://github.com/autonomouslogic/eve-ref/issues/269
=> chore: Extra logging

build.gradle
Related to https://github.com/autonomouslogic/eve-ref/issues/269
=> fix(deps): Update MVStore to 2.2.222

ui/refdata/index.ts
Mitigates duplicate requests from being made.
=> feat: Cache loaded reference data in the UI

src/main/java/com/autonomouslogic/everef/cli/marketorders/ScrapeMarketOrders.java
Should now run in 2-3 minutes instead of 7-8.
=> fix: Removed MVStore from scrape market orders to speed it up

src/main/java/com/autonomouslogic/everef/cli/DataIndex.java, src/main/java/com/autonomouslogic/everef/s3/HeadObjectFlowableTransformer.java, src/main/java/com/autonomouslogic/everef/s3/S3Adapter.java, src/test/java/com/autonomouslogic/everef/cli/DataIndexTest.java
=> feat: Use src_last_modified_millis header for last-modified timestamps on data index

src/main/java/com/autonomouslogic/everef/cli/refdata/BuildRefData.java, src/main/java/com/autonomouslogic/everef/cli/refdata/ObjectMerger.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/BlueprintDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/GroupsDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/MarketGroupsDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/MissingDogmaUnitsDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/MutaplasmidDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/OreVariationsDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/PostDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/SkillDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/TypesDecorator.java, src/main/java/com/autonomouslogic/everef/cli/refdata/post/VariationsDecorator.java, src/test/java/com/autonomouslogic/everef/cli/refdata/ObjectMergerTest.java
=> fix: Object merges don't merge null or empty-strings

src/main/java/com/autonomouslogic/everef/cli/publishrefdata/TypeBundleRenderer.java
=> fix: Fixed nullpointer in publish ref data

docs/src/commands/import-market-history.md, src/main/java/com/autonomouslogic/everef/cli/markethistory/imports/ImportMarketHistory.java, src/main/java/com/autonomouslogic/everef/config/Configs.java, src/main/java/com/autonomouslogic/everef/db/MarketHistoryDao.java, src/test/java/com/autonomouslogic/everef/cli/markethistory/imports/ImportMarketHistoryTest.java
=> fix: IMPORT_MARKET_HISTORY_MIN_DATE defaults to the latest date or today, minus 450 days

Makefile, ui/components/cards/BlueprintManufacturing.vue, ui/components/cards/BlueprintManufacturingLinks.vue, ui/components/cards/TypeManufacturing.vue, ui/components/cards/market/MarketLinks.vue, ui/components/helpers/ExternalLink.vue
=> feat: Added Fuzzwork manufacturing link

ui/components/cards/BlueprintManufacturingLinks.vue
=> feat: Added Adam4EVE manufacturing link

ui/i18n.config.ts, ui/nuxt.config.ts, ui/package-lock.json, ui/package.json
Updated `@nuxtjs/i18n` from `8.0.0-beta-10` to `8.0.0`
Following https://v8.i18n.nuxtjs.org/options/vue-i18n and https://stackblitz.com/edit/jahidanowar-nuxt3-i18n-tutorial-1dtqmo.
=> chore(deps): Updated @nuxtjs/i18n to 8.0.0

ui/components/cards/VariationsCard.vue, ui/components/cards/market/MarketRow.vue, ui/components/compare/CompareTable.vue, ui/components/compare/CompareTableCell.vue, ui/components/compare/CompareTableHorizontal.vue, ui/components/compare/CompareTableVertical.vue, ui/components/dogma/UnitValue.vue, ui/components/dogma/units/Datetime.vue, ui/components/dogma/units/Money.vue, ui/components/helpers/MetaGroupName.vue, ui/lib/mainDogmaAttributes.ts, ui/pages/market-groups/[marketGroupId].vue, ui/pages/privacy.vue, ui/pages/structures/index.vue, ui/pages/types/[typeId].vue
=> feat(ui): Basic comparison of ship variations

ui/components/cards/IndustryCard.vue, ui/components/types/TypeCardSelector.vue, ui/conf/typeCardsConfig.ts
=> feat(ui): Industry card with link to Adam4Eve material influence

ui/components/dogma/units/Money.vue, ui/components/helpers/FormattedNumber.vue, ui/components/skillpoints/Accelerators.vue, ui/components/skillpoints/Accounts.vue, ui/components/skillpoints/Implants.vue, ui/components/skillpoints/Injectors.vue, ui/components/skillpoints/Packs.vue, ui/lib/skillUtils.ts, ui/pages/skill-points.vue
=> feat(ui): Added attribute breakdown for accounts

spec/reference-data.yaml, src/main/java/com/autonomouslogic/everef/refdata/Bundle.java, ui/refdata/index.ts
Closes https://github.com/autonomouslogic/eve-ref/issues/624
Closes https://github.com/autonomouslogic/eve-ref/issues/625
Closes https://github.com/autonomouslogic/eve-ref/issues/626
Depends on https://github.com/autonomouslogic/eve-ref/pull/623
=> feat(ui): Added support for bundles market groups, categories, and groups

ui/lib/translate.ts, ui/pages/categories/[categoryId].vue, ui/pages/categories/index.vue, ui/pages/dogma-attributes/index.vue, ui/pages/market-groups/[marketGroupId].vue, ui/pages/market-groups/index.vue, ui/pages/structures/index.vue
- Spacing for easier use on Mobile
- Multiple columns
It would be nice if the categories were alphabetised but I understand why they're not.
=> fix(ui): Improved layout on list pages

ui/components/cards/UsageCard.vue, ui/components/types/TypeCardSelector.vue, ui/conf/typeCardsConfig.ts
=> feat(ui): Added usage card for showing what can be fitted to a ship

ui/components/MotdBanner.vue
=> fix(ui): Removed conditional MOTD

src/main/java/com/autonomouslogic/everef/cli/BuildSearch.java, src/main/java/com/autonomouslogic/everef/s3/S3Util.java, ui/plugins/preload.server.ts
* Makes `search.json` be uploaded with `cache-control: immutable`
* Adds a prefetch directing in the HTML to load `search.json` on page-load
Closes #632
=> fix: Search optimisation

build.gradle, renovate.json, renovate.md, src/main/java/com/autonomouslogic/everef/inject/S3Module.java
=> fix: Configure checksum calculations to be compatible with Backblaze B2

docs/src/api/industry-cost.md, spec/eve-ref-api.yaml, src/main/java/com/autonomouslogic/everef/industry/IndustryCalculator.java, src/main/java/com/autonomouslogic/everef/industry/InventionCalculator.java, src/main/java/com/autonomouslogic/everef/model/api/ActivityCost.java, src/main/java/com/autonomouslogic/everef/model/api/InventionCost.java, src/main/java/com/autonomouslogic/everef/model/api/MaterialCost.java, src/main/java/com/autonomouslogic/everef/util/MathUtil.java, src/test/java/com/autonomouslogic/everef/api/IndustryCostHandlerTest.java, src/test/resources/com/autonomouslogic/everef/api/IndustryCostHandlerTest/mjolnir-fury-cruise-missile-blueprint-optimized-attainment-decryptor/output.json, src/test/resources/com/autonomouslogic/everef/api/IndustryCostHandlerTest/mjolnir-fury-cruise-missile-blueprint/output.json, src/test/resources/com/autonomouslogic/everef/api/IndustryCostHandlerTest/mjolnir-fury-cruise-missile/output.json, src/test/resources/com/autonomouslogic/everef/api/IndustryCostHandlerTest/sin-blueprint-lowsec-sotiyo-rigs/output.json, src/test/resources/com/autonomouslogic/everef/api/IndustryCostHandlerTest/sin-blueprint/output.json, src/test/resources/com/autonomouslogic/everef/api/IndustryCostHandlerTest/sin/esi-market-prices.json, src/test/resources/com/autonomouslogic/everef/api/IndustryCostHandlerTest/sin/input.json, src/test/resources/com/autonomouslogic/everef/api/IndustryCostHandlerTest/sin/output.json
=> feat(api): Selecting a T2 product for manufacture includes invention

spec/eve-ref-api.yaml, src/main/java/com/autonomouslogic/everef/cli/SyncFuzzworkOrdersets.java, src/main/java/com/autonomouslogic/everef/cli/api/ApiRunner.java, src/main/java/com/autonomouslogic/everef/config/Configs.java, src/main/java/com/autonomouslogic/everef/industry/IndustryCalculator.java, src/main/java/com/autonomouslogic/everef/industry/IndustryMath.java, src/main/java/com/autonomouslogic/everef/industry/InventionCalculator.java, src/main/java/com/autonomouslogic/everef/industry/ManufactureCalculator.java, src/main/java/com/autonomouslogic/everef/model/api/IndustryCostInput.java, src/main/java/com/autonomouslogic/everef/model/api/PriceSource.java, src/main/java/com/autonomouslogic/everef/model/fuzzwork/FuzzworkAggregatedMarketSegment.java, src/main/java/com/autonomouslogic/everef/model/fuzzwork/FuzzworkAggregatedMarketType.java, src/main/java/com/autonomouslogic/everef/service/EsiMarketPriceService.java, src/main/java/com/autonomouslogic/everef/service/FuzzworkMarketService.java, src/main/java/com/autonomouslogic/everef/service/MarketPriceService.java, src/main/java/com/autonomouslogic/everef/util/EveConstants.java, src/test/java/com/autonomouslogic/everef/api/IndustryCostHandlerTest.java, src/test/java/com/autonomouslogic/everef/service/FuzzworkMarketServiceTest.java, src/test/java/com/autonomouslogic/everef/test/TestComponent.java
=> feat(api): Material market prices on industry cost API

.github/workflows/data-checks.yml, Makefile, scripts/run-make-and-check-changes.sh, src/main/java/com/autonomouslogic/everef/cli/refdata/BuildRefData.java
=> chore: Test resources check task

ui/components/cards/TypeInfoCard.vue, ui/components/compare/CompareTableHorizontal.vue, ui/components/compare/CompareTableVertical.vue, ui/components/helpers/MetaGroupLink.vue, ui/components/navbar.vue, ui/pages/meta-groups/[metaGroupId].vue, ui/pages/meta-groups/index.vue
=> feat(ui): Meta group pages

ui/components/cards/market/MarketCardInner.vue, ui/lib/marketUtils.ts, ui/lib/regionConstants.ts, ui/pages/giveaways.vue
=> fix(ui): PLEX prices and August giveaways
